/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "transfer.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

FileChunk *
read_file_1(Params *argp, CLIENT *clnt)
{
	static FileChunk clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, READ_FILE,
		(xdrproc_t) xdr_Params, (caddr_t) argp,
		(xdrproc_t) xdr_FileChunk, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
