/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "transfer.h"

bool_t
xdr_FileChunk (XDR *xdrs, FileChunk *objp)
{
	register int32_t *buf;

	 if (!xdr_bytes (xdrs, (char **)&objp->data.data_val, (u_int *) &objp->data.data_len, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->bytes_read))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Params (XDR *xdrs, Params *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filename, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
