/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRANSFER_H_RPCGEN
#define _TRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct FileChunk {
	struct {
		u_int data_len;
		char *data_val;
	} data;
	int bytes_read;
};
typedef struct FileChunk FileChunk;

struct Params {
	char *filename;
	int offset;
	int size;
};
typedef struct Params Params;

#define FILE_TRANSFER_PROG 0x31230000
#define FILE_TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define READ_FILE 1
extern  FileChunk * read_file_1(Params *, CLIENT *);
extern  FileChunk * read_file_1_svc(Params *, struct svc_req *);
extern int file_transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define READ_FILE 1
extern  FileChunk * read_file_1();
extern  FileChunk * read_file_1_svc();
extern int file_transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_FileChunk (XDR *, FileChunk*);
extern  bool_t xdr_Params (XDR *, Params*);

#else /* K&R C */
extern bool_t xdr_FileChunk ();
extern bool_t xdr_Params ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TRANSFER_H_RPCGEN */
